dist: bionic
language: java
jdk:
  - openjdk11
  - openjdk15
  - openjdk16
  - openjdk-ea
install:
  - mvn dependency:tree test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
#  - mvn test -B -X
matrix:
  fast_finish: true
  allow_failures:
# openjdk11 from install-jdk is 11.0.2 and not the latest
    - jdk: openjdk11
    - jdk: openjdk16
    - jdk: openjdk-ea
