dist: bionic
language: java
jdk:
  - openjdk11
  - openjdk14
  - openjdk15
  - openjdk-ea
env:
  global:
    - DROPWIZARD_VERSION="2.0.5"
before_install: # hack around jpms issue with the dropwizard jars
  - mvn dependency:get -Dartifact=io.dropwizard:dropwizard-core:$DROPWIZARD_VERSION:jar
  - unzip ~/.m2/repository/io/dropwizard/dropwizard-core/$DROPWIZARD_VERSION/dropwizard-core-$DROPWIZARD_VERSION.jar io/dropwizard/validation/InjectValidatorFeature.class
  - zip -d ~/.m2/repository/io/dropwizard/dropwizard-core/$DROPWIZARD_VERSION/dropwizard-core-$DROPWIZARD_VERSION.jar io/dropwizard/validation/InjectValidatorFeature.class
  - zip ~/.m2/repository/io/dropwizard/dropwizard-validation/$DROPWIZARD_VERSION/dropwizard-validation-$DROPWIZARD_VERSION.jar io/dropwizard/validation/InjectValidatorFeature.class
  - rm -rf io/
install:
  - mvn dependency:tree test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
#  - mvn test -B -X
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk15
    - jdk: openjdk-ea
