language: java
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
install:
  - mvn test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk14

