---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11-jdk-slim

inputs:
  - name: test-rp
  - name: test-rp-version

outputs:
  - name: test-rp-java

caches:
  - path: ../../../root/.gradle/caches
  - path: ../../../root/.gradle/wrapper

run:
  path: /bin/sh
  args:
    - -c
    - |
      cd test-rp
      ./gradlew distZip -Pversion=$(cat ../test-rp-version/number) --no-daemon
      cp build/distributions/test-rp-*.zip ../test-rp-java
