openapi: 3.0.0
info:
  description: |
    This is a description of the API for the Verify Service Provider when it's connected to a [Matching Service Adapter](https://github.com/alphagov/verify-matching-service-adapter).

    If you don't have a Matching Service Adapter, see the [API documentation for services connecting using only the Verify Service Provider](https://alphagov.github.io/verify-service-provider/api/verify-service-provider-with-matching-api.swagger.html).

    The API allows you to generate a SAML authentication request and to translate a SAML response into JSON. To use the Verify Service Provider, you must [download your own version](https://github.com/alphagov/verify-service-provider/releases).
  version: 2.0.0
  title: Verify Service Provider
  x-logo:
    url: 'https://github.com/alphagov/verify-service-provider/blob/master/docs/api/verify-logo-redoc.png?raw=true'
    altText: GOV.UK Verify logo
paths:
  /generate-request:
    post:
      summary: Generate a SAML authentication request
      description:  Generate a SAML authentication request, known as an AuthnRequest, to send to Verify Hub.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGenerationBody'
        required: true
      responses:
        '200':
          description: >-
            Contains an object with a valid SAML Authentication request that can
            be consumed by the GOV.UK Verify Hub.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponseBody'
        '422':
          description: >-
            An error due to a JSON request in an invalid format for example, missing required parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 422
                message: A description of the error
        '500':
          description: An error due to an internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 500
                message: A description of the error
  /translate-response:
    post:
      summary: Translate a SAML response
      description: >-
        Translate a SAML response received from the GOV.UK Verify Hub into JSON.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateSamlResponseBody'
        description: An object containing the SAML response returned by the GOV.UK Verify Hub.
        required: true
      responses:
        '200':
          description: 'Contains the details of the SAML response, translated into JSON.'
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/SuccessfulMatchResponseBody'
                - $ref: '#/components/schemas/AccountCreationResponseBody'
                - $ref: '#/components/schemas/NoMatchResponseBody'
                - $ref: '#/components/schemas/CancellationResponseBody'
                - $ref: '#/components/schemas/AuthenticationFailedResponseBody'
                - $ref: '#/components/schemas/RequestErrorResponseBody'
        '400':
          description: An error due to a problem with translating the Response.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 400
                message: A description of the error
        '422':
          description: >-
            An error due to a JSON request in an invalid format, for example missing
            required parameters).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 422
                message: A description of the error
        '500':
          description: An error due to an internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 500
                message: A description of the error
components:
  schemas:
    RequestGenerationBody:
      type: object
      properties:
        entityId:
          $ref: '#/components/schemas/EntityId'
    RequestResponseBody:
      type: object
      required:
        - samlRequest
        - requestId
        - ssoLocation
      properties:
        samlRequest:
          description: 'SAML authentication request as a base64 string.'
          type: string
          format: byte
        requestId:
          description: >-
            A token that identifies the authentication request. This is used later to verify that the authentication request and SAML response have passed through the same browser.
          type: string
          format: byte
        ssoLocation:
          description: >-
            The GOV.UK Verify Hub URL where your service sends the authentication request.
          type: string
          format: url
    TranslateSamlResponseBody:
      type: object
      required:
        - samlResponse
        - requestId
        - levelOfAssurance
      properties:
        samlResponse:
          description: 'A SAML response as a base64 string.'
          type: string
          format: byte
        requestId:
          description: >-
            A token that was generated for the original SAML authentication request. This is used to verify that the authentication request and SAML response have passed through the same browser.
          type: string
          format: byte
        levelOfAssurance:
          $ref: '#/components/schemas/RequiredLevelOfAssurance'
        entityId:
          $ref: '#/components/schemas/EntityId'
    SuccessfulMatchResponseBody:
      type: object
      description: Returned when the user has been successfully matched to your local datastore.
      properties:
        scenario:
          type: string
          enum:
            - SUCCESS_MATCH
          description: Returned when the user has been successfully matched to your local datastore.
        pid:
          description: >-
            A unique identifier that can identify a user against an internal
            record.
          type: string
          format: byte
        levelOfAssurance:
          $ref: '#/components/schemas/ReceivedLevelOfAssurance'
    AccountCreationResponseBody:
      type: object
      description: Returned when the user has not been successfully matched to your local datastore, but your service supports the creation of accounts.
      properties:
        scenario:
          type: string
          enum:
            - ACCOUNT_CREATION
          description: Returned when the user has not been successfully matched to your local datastore, but your service supports the creation of accounts.
        pid:
          description: >-
            A unique identifier that can identify a user against an internal
            record.
          type: string
          format: byte
        levelOfAssurance:
          $ref: '#/components/schemas/ReceivedLevelOfAssurance'
        attributes:
          $ref: '#/components/schemas/AccountCreationAttributes'
    NoMatchResponseBody:
      description: Returned when the user has not been successfully matched to your local datastore
      type: object
      properties:
        scenario:
          type: string
          enum:
            - NO_MATCH
          description: Returned when the user has not been successfully matched to your local datastore
    CancellationResponseBody:
      description: Returned when the user has cancelled
      type: object
      properties:
        scenario:
          type: string
          enum:
            - CANCELLATION
          description: Returned when the `urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext` status code is included in the SAML response from the GOV.UK Verify Hub.
    RequestErrorResponseBody:
      description: Returned when there was an error in the request.
      type: object
      properties:
        scenario:
          type: string
          enum:
            - REQUEST_ERROR
          description: Returned when there was an error in the request.
    AuthenticationFailedResponseBody:
      description: Returned when there was a failure to authenticate.
      type: object
      properties:
        scenario:
          type: string
          enum:
            - AUTHENTICATION_FAILED
          description: Returned when there was a failure to authenticate.
    RequiredLevelOfAssurance:
      description: The minimum level of assurance required by the service.
      type: string
      enum:
        - LEVEL_1
        - LEVEL_2
    EntityId:
      description: >-
        The EntityId for the service interacting with the Verify Service Provider. This is required if there is more than one service connected to the same Verify Service Provider deployment, otherwise it is optional. The value, if provided, must be one of those listed in the configuration for the Verify Service Provider.
      type: string
    ReceivedLevelOfAssurance:
      description: Level of assurance the user's identity was verified with.
      type: string
      enum:
        - LEVEL_1
        - LEVEL_2
    AccountCreationAttributes:
      description: >-
        When user-account-creation is supported by the service, and no
        match was possible, these attributes are used to create a new account.
      type: object
      properties:
        firstName:
          type: object
          properties:
            value:
              type: string
            verified:
              type: boolean
        middleName:
          type: object
          properties:
            value:
              type: string
            verified:
              type: boolean
        surname:
          type: object
          properties:
            value:
              type: string
            verified:
              type: boolean
        dateOfBirth:
          type: object
          properties:
            value:
              type: string
              format: date
            verified:
              type: boolean
        address:
          type: object
          properties:
            value:
              $ref: '#/components/schemas/Address'
            verified:
              type: boolean
        addressHistory:
          type: array
          items:
            type: object
            properties:
              value:
                $ref: '#/components/schemas/Address'
              verified:
                type: boolean
        cycle3:
          type: string
    Address:
      description: >-
        An object describing the address fields of a user
      type: object
      properties:
        lines:
          type: array
          items:
            type: string
        postCode:
          type: string
        internationalPostCode:
          type: string
        uprn:
          type: string
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
    ErrorMessage:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          description: The HTTP status code
        message:
          description: A description of the error
          type: string
