openapi: 3.0.0
info:
  description: |
    This is a description of the API for the Verify Service Provider.

    The API allows you to generate a SAML authentication request and to translate a SAML response into JSON. To use the Verify Service Provider, you must [download your own version](https://github.com/alphagov/verify-service-provider/releases).

    If you are using the legacy setup involving a [Matching Service Adapter](https://github.com/alphagov/verify-matching-service-adapter), see the [API documentation for the legacy setup](https://alphagov.github.io/verify-service-provider/api/verify-service-provider-with-matching-api.swagger.html).
  version: 2.0.0
  title: Verify Service Provider
  x-logo:
    url: 'https://github.com/alphagov/verify-service-provider/blob/master/docs/api/verify-logo-redoc.png?raw=true'
    altText: GOV.UK Verify logo
externalDocs:
  description: Find out more about setting up the Verify Service Provider.
  url: 'https://www.docs.verify.service.gov.uk/get-started/set-up-successful-verification-journey/#set-up-the-successful-verification-user-journey'
paths:
  /generate-request:
    post:
      summary: Generate a SAML authentication request
      description: |
        Generate a SAML authentication request, known as an AuthnRequest, to send to Verify Hub.

        See the GOV.UK Verify technical  documentation for more information on [how to generate an authentication request](https://www.docs.verify.service.gov.uk/get-started/set-up-successful-verification-journey/#send-a-request).
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGenerationBody'
        required: true
      responses:
        '200':
          description: >-
            Contains an object with a valid SAML authentication request that can be consumed by the GOV.UK Verify Hub.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponseBody'
        '422':
          description: >-
            An error due to a JSON request in an invalid format, for example missing required parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 422
                message: Some error message
        '500':
          description: An error due to an internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 500
                message: Some error message
  /translate-response:
    post:
      summary: Translate a SAML response
      description: |
        Translate a SAML response received from the GOV.UK Verify Hub into JSON.

        See the GOV.UK Verify technical documentation for more information on [how to handle the response](https://www.docs.verify.service.gov.uk/get-started/set-up-successful-verification-journey/#handle-a-response)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateSamlResponseBody'
        description: An object containing the SAML response returned by the GOV.UK Verify Hub.
        required: true
      responses:
        '200':
          description: 'Contains the details of the SAML response, translated into JSON.'
          content:
            application/json:
              schema:
               oneOf:
                  - $ref: '#/components/schemas/IdentityVerificationScenario'
                  - $ref: '#/components/schemas/AuthenticationFailedScenario'
                  - $ref: '#/components/schemas/NoAuthenticationScenario'
                  - $ref: '#/components/schemas/RequestErrorScenario'
        '400':
          description: An error due to a problem with translating the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 400
                message: Some error message
        '422':
          description: >-
            An error due to a JSON request in an invalid format, for example missing required parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 422
                message: Some error message
        '500':
          description: An error due to an internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                code: 500
                message: Some error message
components:
  schemas:
    RequestGenerationBody:
      type: object
      properties:
        entityId:
          $ref: '#/components/schemas/EntityId'
    RequestResponseBody:
      type: object
      required:
        - samlRequest
        - requestId
        - ssoLocation
      properties:
        samlRequest:
          description: SAML authentication request as a base64 string.
          type: string
          format: byte
        requestId:
          description: >-
            A token that identifies the authentication request. This is used later to verify that the authentication request and SAML response have passed through the same browser.
          type: string
          format: byte
        ssoLocation:
          description: >-
            The GOV.UK Verify Hub URL where your service sends the authentication request.
          type: string
          format: url
    TranslateSamlResponseBody:
      type: object
      required:
        - samlResponse
        - requestId
        - levelOfAssurance
      properties:
        samlResponse:
          description: A SAML response as a base64 encoded string.
          type: string
          format: byte
        requestId:
          description: >-
            A token that was generated for the original SAML authentication request. This is used to verify that the SAML authentication request and SAML response have passed  through the same browser.
          type: string
          format: byte
        levelOfAssurance:
          $ref: '#/components/schemas/RequiredLevelOfAssurance'
    RequestErrorScenario:
      description: Returned when there was an error in the request.
      type: object
      required:
        - scenario
      properties:
        scenario:
          type: string
          enum:
            - REQUEST_ERROR
          description: Returned when there was an error in the request.
    AuthenticationFailedScenario:
      description: Returned when the `urn:oasis:names:tc:SAML:2.0:status:AuthnFailed` status code is included in the SAML response from the GOV.UK Verify Hub.
      type: object
      required:
        - scenario
      properties:
        scenario:
          type: string
          enum:
            - AUTHENTICATION_FAILED
          description: Returned when the `urn:oasis:names:tc:SAML:2.0:status:AuthnFailed` status code is included in the SAML response from the GOV.UK Verify Hub.
    NoAuthenticationScenario:
      description: Returned when the `urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext` status code is included in the SAML response from the GOV.UK Verify Hub.
      type: object
      required:
        - scenario
      properties:
        scenario:
          type: string
          enum:
            - NO_AUTHENTICATION
          description: Returned when the `urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext` status code is included in the SAML response from the GOV.UK Verify Hub.
    IdentityVerificationScenario:
      description: Returned when the user's identity was successfully verified
      type: object
      required:
        - scenario
        - pid
        - attributes
        - levelOfAssurance
      properties:
        scenario:
          type: string
          enum:
          - IDENTITY_VERIFIED
          description: Returned when the user's identity was successfully verified
        pid:
          description: >-
            A unique identifier that can identify a user against an internal
            record.
          type: string
          format: byte
        levelOfAssurance:
          $ref: '#/components/schemas/ReceivedLevelOfAssurance'
        attributes:
          $ref: '#/components/schemas/Attributes'
    RequiredLevelOfAssurance:
      description: The minimum level of assurance required by the service.
      type: string
      enum:
        - LEVEL_1
        - LEVEL_2
        - LEVEL_3
        - LEVEL_4
    EntityId:
      description: >-
        The EntityId for the service interacting with the Verify Service Provider. This is required if there is more than one service connected to the same Verify Service Provider deployment, otherwise it is optional. The value, if provided, must be one of those listed in the configuration for the Verify Service Provider.
      type: string
    ReceivedLevelOfAssurance:
      description: Level of assurance the user's identity was verified with.
      type: string
      enum:
        - LEVEL_1
        - LEVEL_2
        - LEVEL_3
        - LEVEL_4
    Attributes:
      description: >-
        An object containing the user attributes returned from the identity provider.
      type: object
      properties:
        firstNames:
          type: array
          items:
            $ref: '#/components/schemas/PersonalName'
        middleNames:
          type: array
          items:
            $ref: '#/components/schemas/PersonalName'
        surnames:
          type: array
          items:
            $ref: '#/components/schemas/PersonalName'
        datesOfBirth:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/VerifiableAttribute'
              - properties:
                  value:
                    $ref: '#/components/schemas/Date'
        gender:
          type: object
          properties:
            verified:
              type: boolean
            value:
              type: string
              enum:
                - FEMALE
                - MALE
                - NOT_SPECIFIED
                - OTHER
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/VerifiableAddress'
    Date:
      type: string
      format: date
    VerifiableAttribute:
      type: object
      properties:
        verified:
          type: boolean
        from:
          $ref: '#/components/schemas/Date'
        to:
          $ref: '#/components/schemas/Date'
    PersonalName:
      allOf:
      - $ref: '#/components/schemas/VerifiableAttribute'
      - description: 'An object describing a forename, middlename or surname'
        properties:
          value:
            type: string
          nonLatinScriptValue:
            type: string
    VerifiableAddress:
      allOf:
        - $ref: '#/components/schemas/VerifiableAttribute'
        - description: An object describing the address fields of a user
          properties:
            value:
              $ref: '#/components/schemas/Address'
    Address:
      type: object
      description: An object describing the address fields of a user
      properties:
        lines:
          type: array
          items:
            type: string
        postCode:
          type: string
        internationalPostCode:
          type: string
        uprn:
          type: string
    ErrorMessage:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
        message:
          type: string
