name: Java CI with Maven

on:
  push:
    branches: [ monorepo ]
  pull_request:
    branches: [ monorepo ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B clean test package --file pom.xml
